name: Creative Ai
favicon: null
layout_spectrum: 1
typography_spectrum: 0.63776
title: Creativity and Artificial Intelligence
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#192943'
    - '#7b8aa1'
    - '#f4bf7d'
    - '#73594a'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose: []
