name: Creative Ai
favicon: null
layout_spectrum: 0.51304
typography_spectrum: 0.63776
title: Creativity and Artificial Intelligence
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#aeaeae'
    - '#323232'
    - '#725945'
    - '#197993'
  brandStrength: 0
  lightness: 0
  saturation: 0.125
  rhythmicContrast: 0
purpose: []
